
<!doctype html>

<html>

	<head>
		<meta charset="utf-8">
		<title>Charles Herzfeld -- Project 3</title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body>

		<div class="container">

		<?php include "inc/header.php" ?>

			<div class="headerbox">
			

				<!--
				<header>
		            <h1>Charles Herzfeld</h1>
		        </header>

		        <?php include "inc/nav.inc" ?>
		    	-->

	    	</div>

		<article>

			<h2 id="story">A story about Charles Herzfeld</h2>

			<p>There are a thousand stories about the origin of the Internet, each with their own starting point and their own heroes. Charles Herzfeld’s tale began in 1961 on a series of tiny islands in the South Pacific. The U.S. military was test-firing a series of ballistic missiles at the island chain, known as the Kwajalein Atoll, with an array of radars and optical infrared sensors recording every re-entry. Herzfeld, the Vienna-born physicist and newly installed chief of the Advanced Research Projects Agency’s missile defense program, was trying to figure out how to make sense of the vast amount of data generated by all of those incoming missiles. The computers he had at the time weren’t up to the task.</p>

			<p>Herzfeld, in search of solutions, asked his colleague J.C.R. Licklider out to lunch. They met at the Secretary of Defense’s Mess in the Pentagon’s E Ring, and over a series of meals talked through ideas that would transform computing forever.</p>

			<div class="figcontainer">
			<figure>
	        	<img src="images/researchers.jpeg" alt="ARPA researchers">
	        	<figcaption>Charles Herzfeld (center, white shirt) with other researchers</figcaption>
        	</figure>
        	</div>

			<p>Licklider, the head of of ARPA’s Information Processing Techniques Office, was already one of computer science’s leading thinkers. (“Licklider was our prophet. I signed onto his vision from the beginning,” Herzfeld says.) Not only did Licklider predict that one day “human brains and computing machines will be coupled” into a partnership that would surpass either component’s ability to process information. Licklider theorized that people could one day interact with all sorts of computers at once — even though each machine had its own programming language and its own control scheme. They would all be part of a single network.
			“Most people don’t understand the experience of doing something absolutely new,” Herzfeld says, more than 50 years after the fact. “This was a new idea, and very radical.”</p>

			<p>Over their E Ring lunches, Herzfeld told Licklider about the mass of data he was generating at the Kwajalein Atoll as his machines tried to discriminate between chaff and missile, between countermeasure and target. Herzfeld funded the development of broadband receivers, electronics that could accept data at an unheard-of rate: 150 megabits per second. He backed new storage media, including a magnetic tape that would one day lead to video cassettes. It wasn’t enough.
			“Look, Lick,” Herzfeld said, “If your [network] idea could be done, it would make all of this much easier.” Researchers could rely on a whole network of machines, not just a single one.

			“You’re right,” Licklider answered. “But it’s too soon.”</p>

			<p>Six years later, the time was right. Herzfeld had ascended to the top position at ARPA. He hired Bob Taylor, a specialist in human-computer interaction, and together they began talking about steps to make Licklider’s vision concrete. That led to a million-dollar grant to begin work on the Arpanet, the internet’s direct predecessor. For funding that all-important work, Herzfeld was inducted earlier this year into the Internet Society’s Internet Hall of Fame, alongside such pioneers as Vint Cerf, Bob Kahn, and Sir Tim Berners-Lee.</p>

			<div class="figcontainer">
	        <figure>
	        	<img src="images/herzfeld.jpg" alt="Charles Herzfeld">
	        	<figcaption>Charles Herzfeld</figcaption>
	        </figure>
	    	</div>

			<p>In some ways, the Internet was as much a product of an institution as of a group of people. ARPA — later renamed DARPA — plucked visionaries like Licklider and Taylor from industry and academia, sucked up their best ideas, and then returned them to their home institutions a few years later. ARPA directors like Herzfeld had a tremendous amount of leeway to set priorities and to spend money as they saw fit; few others in the military research community enjoyed that kind of flexibility. (To this day, that freedom to kill an artificial intelligence project one minute and launch a new soldier enhancement program the next continues to periodically enrage Congress and the Pentagon brass.) Herzfeld believes it’s one of the reasons why his agency — and not some other government group — gave rise to the Internet.</p>

			<p>Still, every new project needed to be justified to his Pentagon bosses. (“We needed a story and it had to be plausible,” Herzfeld remembers.) The story also had to be big. ARPA, in Herzfeld’s opinion, wasn’t designed to take on minor matters. It was supposed to study strategic, Presidential-level issues — at the time, missile defense, nuclear test verification, and mastery of counterinsurgency were the big ones. Then, ARPA was meant to find solutions to those most important and most vexing of problems. Even in an age of ambitious government projects (think Apollo 11), it made ARPA unique.</p>

			<p>The key to unlocking these big ambitions, according to Herzfeld, was to put together a family of research projects that could address a major topic all at once. ”Large programs do better when they have a theme. Most times, there’s a bowl full of beautiful jewels, but there’s no necklace,” Herzfeld says.</p>

			<p>Project AGILE studied every aspect of counterinsurgency — from social dynamics in potential hotbeds like Thailand to new tools of infantry warfare like jet packs. The nuclear inspection programs, VELA and LASA, built satellites to monitor above-ground atomic blasts and revolutionized geophysics by training a series of first-of-its-kind phased array radars to look for hints of tests beneath the Earth’s surface. Licklider’s idea — of a computer network as easy to operate as the telephone — was a necklace all by itself.</p>

			<p>“There were about 100 mainframe computers in the whole country, and about 1,000 to 10,000 people to use them. When it came time to explain why we wanted to do the Arpanet, I told [the Pentagon brass]: I want every investigator to have a console at their desk, where they can find all the tools, all the programs, and all the data to do their work.”</p>

			<p>In a small space next to Taylor’s Pentagon office, there was a kind of advertisement for why such a project was needed. Taylor had three computer terminals, each connected to a separate mainframe. One could communicate with MIT, another with a University of California, Berkeley machine, and a third with an Air Force-built mainframe in Santa Monica, California. Taylor could only interact with one remote site at a time. None of those other researchers could easily pass information to one another. And even if there were such a connection, one machine couldn’t comprehend what the other was saying; each computer was programmed with its own boutique language. The result: wasted time and duplicative research. What they needed was a network, instead.

			The Pentagon bosses approved the $1 million. And Taylor got to work writing a request for proposals for what would become the Arpanet.</p>

			<p>Over the years, the project accumulated all kinds of origin myths. In one version, the Arpanet was supposedly developed as a tool for communicating after a nuclear holocaust. (Not true, but one of the men who came up with the idea of packet-switching, which became the internet’s method for passing along data, was so motivated.) In another version, recounted in the fabulous history Where Wizards Stay Up Late, Herzfeld approved the Arpanet million after a single, 20-minute pitch from Taylor. “That makes me sound like an easy spender, which I was not,” says Herzfeld.</p>

			<div class="factbox">

				<div>

				<h2 id="facts">Key facts about Herzfeld</h2>

				<ul>
					<li>Director of ARPA (Advanced Research Projects Agency) in the 1960s</li>
					<li>Born in Vienna</li>
					<li>Earned BS from Catholic University of America and PhD from University of Chicago</li>
				</ul>

				</div>

				<div>

				<h2 id="timeline">ARPA timeline</h2>

				<table border="1">
					<tr>
						<td>1957</td>
						<td>US creates ARPA in response to USSR's Sputnik launch</td>
					</tr>
					<tr>
						<td>1967</td>
						<td>ARPANET design discussions held in Ann Arbor, Michigan</td>
					</tr>
					<tr>
						<td>1970</td>
						<td>ARPANET Host-Host protocal first published</td>
					</tr>
					<tr>
						<td>1973</td>
						<td>ARPANET forms first international connections</td>
					</tr>
				</table>

				</div>

			</div>

		</article>

		 <footer>
            <h2>Citations</h2>
            <ul>
                <li><a href="http://www.wired.com/2012/08/herzfeld/" target="_blank">How Pacific Island Missile Tests Helped Launch the Internet</a></li>
                <li><a href="http://internethalloffame.org/inductees/charles-herzfeld" target="_blank">Internet Hall of Fame Pioneer: Charles Herzfeld</a></li>
                <li><a href="http://www.zakon.org/robert/internet/timeline/" target="_blank">Hobbes' Internet Timeline 12</a></li>
            </ul>
            This website was created by Samantha Merrill.
        </footer>

    	</div>

    	<?php include "inc/js.inc" ?>

	</body>

</html>


